Update Jenkinsfile3.txt

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -4,7 +4,7 @@ pipeline {
         stage('Test') {
             steps {
                  
-                  echo 'SUCCESS'
+                  echo 'FAILED'; exit 1
             }
         }
     }
